<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "alm_gallery"
 *
 * Auto generated by Extension Builder 2015-04-12
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'AlmGallery',
	'description' => 'A simple folder gallery',
	'category' => 'plugin',
	'author' => 'Andi Platen',
	'author_email' => 'info@wireframe.de',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
